name: CI/CD - Inventario App

on:
  push:
    branches:
      - master

jobs:

  # ==========================================
  # JOB 1: BUILD Y TEST
  # ==========================================
  build-test:
    name: Build y Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: npm ci

      # 4. Ejecutar pruebas
      - name: Ejecutar tests
        run: npm test


  # ==========================================
  # JOB 2: BUILD, TRIVY Y PUSH
  # ==========================================
  build-push:
    name: Build, Scan y Push Docker
    runs-on: ubuntu-latest

    # Este job SOLO se ejecuta si build-test termina correctamente
    needs: build-test

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Descargar código
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Convertir el nombre del repositorio a minúsculas (Requerido por GHCR)
      - name: Configurar nombre de repositorio en minúsculas
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 3. Iniciar sesión en GitHub Container Registry
      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Crear metadata y etiquetas de la imagen
      - name: Configurar etiquetas Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/XavierStalin/inventario-app 
          tags: |
            type=sha
            type=raw,value=latest

      # 5. Construir la imagen Docker (Cargándola localmente con load: true)
      - name: Construir imagen Docker localmente
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ghcr.io/${{ env.REPO_NAME }}:latest

      # 6. Escanear imagen con Trivy
      - name: Escanear imagen con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ghcr.io/${{ env.REPO_NAME }}:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL

      # 7. Publicar imagen en GHCR (Empuja las etiquetas generadas)
      - name: Publicar imagen en GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}